<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNTy2SHF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNTy2SHF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNTy2SHF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNTy2SHF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNTy2SHF\App_KernelDevDebugContainer([
    'container.build_hash' => 'NTy2SHF',
    'container.build_id' => '467a596a',
    'container.build_time' => 1651412381,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNTy2SHF');
